spring:
  cloud:
    config:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306
      database: identity_provider
      username: root
      password:

      initial-size: 20
      max-total: 20
      min-idle: 20
      max-idle: 20

      max-wait-millis: 500
      test-on-borrow: true
      test-on-return: true
      validation-query: SELECT 1


eureka:
  client:
    enabled: false
